logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
insecureSkipVerify = true


[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.jnlp]
    address = ":50000"
  [entryPoints.kerberos]
    address = ":88"
  [entryPoints.kerberos_passwd]
    address = ":464"
  [entryPoints.ldap]
    address = ":389"
  [entryPoints.ldapssl]
    address = ":636"


[api]
  dashboard = true


[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false


[acme]
  email = "it@magfest.org"
  storage = "acme.json"
  onHostRule = true
  onDemand = false
  caServer = "{{ salt['pillar.get']('letsencrypt:ca_server') }}"
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "{{ salt['pillar.get']('master_domain') }}"
    sans = [
  {%- for domain in ['errbot', 'freeipa', 'jenkins', 'traefik'] -%}
    "{{ domain }}.{{ salt['pillar.get']('master_domain') }}"{{ ', ' if not loop.last else '' }}
  {%- endfor -%}]
