logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
insecureSkipVerify = true


[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.jnlp50000]
    address = ":50000"


[api]
  dashboard = true


[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false
  [docker.tls]
    insecureskipverify = true


[acme]
  email = "it@magfest.org"
  storage = "acme.json"
  onHostRule = true
  onDemand = false
  caServer = "https://acme-staging.api.letsencrypt.org/directory"
  entryPoint = "https"
    [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "{{ salt['pillar.get']('master_domain') }}"
    sans = [
  {%- for domain in ['errbot', 'freeipa', 'jenkins', 'traefik'] -%}
    "{{ domain }}.{{ salt['pillar.get']('master_domain') }}"{{ ', ' if not loop.last else '' }}
  {%- endfor -%}]
