logLevel = "DEBUG"
defaultEntryPoints = ["http"]


[entryPoints]
  [entryPoints.http]
    address = ":80"


[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "magfest.net"
  watch = true
  exposedbydefault = false


# [entryPoints]
#   [entryPoints.http]
#   address = ":80"
#     [entryPoints.http.redirect]
#       entryPoint = "https"
#   [entryPoints.https]
#   address = ":443"
#     [entryPoints.https.tls]


# [acme]
# email = "it@magfest.org"
# storage = "acme.json"
# onHostRule = true
# onDemand = false
# caServer = "https://acme-staging.api.letsencrypt.org/directory"
# entryPoint = "https"
#   [acme.httpChallenge]
#   entryPoint = "http"
# [[acme.domains]]
#   main = "magfest.net"
#   sans = ["errbot.magfest.net", "freeipa.magfest.net", "jenkins.magfest.net", "traefik.magfest.net"]
