debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http", "https"]


[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[retry]


[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker_intranet.local"
watch = true
exposedbydefault = false


[acme]
email = "it@magfest.org"
storage = "acme.json"
onHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"
[[acme.domains]]
  main = "errbot.magfest.net"
[[acme.domains]]
  main = "freeipa.magfest.net"
[[acme.domains]]
  main = "jenkins.magfest.net"
[[acme.domains]]
  main = "traefik.magfest.net"


[web]
address = ":8080"
