{%- set freeipa_hostname = salt['pillar.get']('freeipa:server:hostname') -%}
{%- set ca_server = salt['pillar.get']('traefik:caServer') -%}

logLevel = "INFO"
InsecureSkipVerify = true
defaultEntryPoints = ["http", "https"]


[entryPoints]
  [entryPoints.http]
    address = ":80"

    [entryPoints.http.redirect]
      entryPoint = "https"

  [entryPoints.https]
    address = ":443"

    [entryPoints.https.tls]
{% for cert_name in salt['pillar.get']('traefik:cert_names', []) %}
      [[entryPoints.https.tls.certificates]]
        certFile = "/certs/{{ cert_name }}.cert"
        keyFile = "/certs/{{ cert_name }}.key"
{% endfor %}


[api]
  dashboard = true


[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "{{ salt['pillar.get']('traefik:domain') }}"
  watch = true
  exposedbydefault = false


[file]

[backends]
  [backends.salt]
    [backends.salt.servers]
      [backends.salt.servers.server0]
        url = "https://{{ salt['network.interface_ip'](salt['grains.get']('private_interface', 'eth1')) }}:8000"

[frontends]
  [frontends.salt]
    backend = "salt"
    entrypoints = ["http", "https"]
    [frontends.salt.routes.salt]
      rule = "Host:salt.{{ salt['pillar.get']('traefik:domain') }}"


{% if salt['pillar.get']('traefik:letsencrypt_enabled') -%}
[acme]
  email = "it@magfest.org"
  storage = "acme.json"
  onHostRule = false
  onDemand = false
  entryPoint = "https"
  {% if ca_server -%}
  caServer = "{{ ca_server }}"
  {% endif %}
  [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "{{ salt['pillar.get']('traefik:domain') }}"
    sans = [
  {%- for subdomain in salt['pillar.get']('traefik:subdomains', []) -%}
    "{{ subdomain }}.{{ salt['pillar.get']('traefik:domain') }}"{{ ', ' if not loop.last else '' }}
  {%- endfor -%}]
{% endif -%}
