{%- set freeipa_hostname = salt['pillar.get']('freeipa:hostname') -%}

logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
insecureSkipVerify = true


[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]


[api]
  dashboard = true


[acme]
  email = "it@magfest.org"
  storage = "acme.json"
  onHostRule = true
  onDemand = false
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "{{ salt['pillar.get']('master_domain') }}"
    sans = [
  {%- for domain in ['directory', 'errbot', 'jenkins', 'traefik'] -%}
    "{{ domain }}.{{ salt['pillar.get']('master_domain') }}"{{ ', ' if not loop.last else '' }}
  {%- endfor -%}]


[docker]
  endpoint = "unix:///var/run/docker.sock"
  watch = true
  exposedbydefault = false


[file]

  [[tls]]
    entryPoints = ["https"]
    [tls.certificate]
      # Default cert to use when no SNI match is found
      certFile = "/certs/{{ freeipa_hostname }}.cert"
      keyFile = "/certs/{{ freeipa_hostname }}.key"
