{%- set freeipa_hostname = salt['pillar.get']('freeipa:hostname') -%}

logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
insecureSkipVerify = true


[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
        # Default cert to use when no SNI match is found
        certFile = "/certs/{{ freeipa_hostname }}.cert"
        keyFile = "/certs/{{ freeipa_hostname }}.key"


[api]
  dashboard = true


[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "{{ salt['pillar.get']('master:domain') }}"
  watch = true
  exposedbydefault = false


[acme]
  email = "it@magfest.org"
  storage = "acme.json"
  onHostRule = false
  onDemand = false
  caServer = "https://acme-staging.api.letsencrypt.org/directory"
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "{{ salt['pillar.get']('master:domain') }}"
    sans = [
  {%- for domain in ['directory', 'errbot', 'hal', 'jenkins', 'traefik'] -%}
    "{{ domain }}.{{ salt['pillar.get']('master:domain') }}"{{ ', ' if not loop.last else '' }}
  {%- endfor -%}]
