{%- set freeipa_hostname = salt['pillar.get']('freeipa:hostname') -%}

logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]
insecureSkipVerify = true


[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
      {% for cert_name in salt['pillar.get']('traefik:cert_names', []) %}
      [[entryPoints.https.tls.certificates]]
        certFile = "/certs/{{ cert_name }}.cert"
        keyFile = "/certs/{{ cert_name }}.key"
      {% endfor %}

[api]
  dashboard = true


[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "{{ salt['pillar.get']('traefik:domain_name') }}"
  watch = true
  exposedbydefault = false


[acme]
  email = "it@magfest.org"
  storage = "acme.json"
  onHostRule = false
  onDemand = false
  caServer = "https://acme-staging.api.letsencrypt.org/directory"
  entryPoint = "https"
  [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "{{ salt['pillar.get']('traefik:domain_name') }}"
    sans = [
  {%- for subdomain in salt['pillar.get']('traefik:subdomains', []) -%}
    "{{ subdomain }}.{{ salt['pillar.get']('traefik:domain_name') }}"{{ ', ' if not loop.last else '' }}
  {%- endfor -%}]
